### ISSUE TITLE
如何将v2-node.service安装到节点服务器

### ISSUE THREAD

**Issue by unkosun** [StyleTJy/v2-ui#1]
v2-node.service是否有其他依赖？

有没有脚本可以一键部署到节点服务器？

**Comment by 690933449** [comment]
> v2-node.service是否有其他依赖？
> 
> 有没有脚本可以一键部署到节点服务器？

这个其实可以参考[install.sh](https://github.com/690933449/v2-ui/blob/master/install.sh)里 install_v2-ui 的步骤就好了。
我把步骤提炼一下吧，脚本的话后期再加上来
```shell
cp -f v2-node.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable v2-node
systemctl start v2-node
```
后面再用 `service v2-node start|stop|status` 命令就可以操作了
